### ISSUE TITLE
Error: Unable to parse JSON response

### ISSUE THREAD

**Issue by bvj** [wintercms/web-installer#25]
Using web installer i am getting:

```
Sorry, but an error has occurred while trying to install Winter CMS.

Error: Unable to parse JSON response

```
I have set max_execution_time to 360, but it did not helped.

**Comment by bennothommo** [comment]
@bvj sorry for the delay in responding.

Do you have a `install.log` file that we can review?

**Comment by bvj** [comment]
Now tried last installer and finished OK.

**Comment by stareu** [comment]
I have the same error.
I tried to increase `max_execution_time` in php.ini and tried the latest version from [here](https://github.com/wintercms/web-installer/releases/tag/v1.0.0).
It didn't help.

My install.log:
```
[2022-01-29 20:24:11+01:00] INFO: Installer API request received {"method":"GET","endpoint":"checkApi"} 
ion"} 
} 
[2022-01-29 20:24:11+01:00] NOTICE: Trying Winter CMS API  
nsion  
[2022-01-29 20:24:11+01:00] NOTICE: Compared PHP version {"installed":"8.1.1","needed":"7.2.9"} 
[2022-01-29 20:24:11+01:00] NOTICE: Checking PHP "json" extension  
[2022-01-29 20:24:11+01:00] NOTICE: PHP version requirement met.  
[2022-01-29 20:24:11+01:00] NOTICE: Checking PHP "pdo" extension  
[2022-01-29 20:24:11+01:00] NOTICE: Checking PHP "zip" extension  
[2022-01-29 20:24:11+01:00] NOTICE: Checking PHP "mbstring" extension  
[2022-01-29 20:24:11+01:00] INFO: Winter API request {"method":"GET","uri":"ping"} 
[2022-01-29 20:24:11+01:00] NOTICE: Checking PHP "fileinfo" extension  
[2022-01-29 20:24:11+01:00] NOTICE: Checking PHP "openssl" extension  
[2022-01-29 20:24:11+01:00] NOTICE: Checking PHP "gd" extension  
[2022-01-29 20:24:11+01:00] NOTICE: Checking PHP "filter" extension  
[2022-01-29 20:24:11+01:00] NOTICE: Checking PHP "hash" extension  
[2022-01-29 20:24:11+01:00] NOTICE: Checking PHP "dom" extension  
[2022-01-29 20:24:11+01:00] NOTICE: Required PHP extensions are installed.  
[2022-01-29 20:24:12+01:00] NOTICE: Response received from Winter CMS API {"response":"pong"} 
[2022-01-29 20:24:12+01:00] NOTICE: Winter CMS API connection successful.  
[2022-01-29 20:24:31+01:00] INFO: Installer API request received {"method":"POST","endpoint":"checkDatabase"} 
[2022-01-29 20:24:31+01:00] NOTICE: Check database connection  
[2022-01-29 20:24:31+01:00] INFO: Installer API request received {"method":"GET","endpoint":"checkWriteAccess"} 
[2022-01-29 20:24:31+01:00] NOTICE: Current working directory is writable.  
[2022-01-29 20:24:31+01:00] ERROR: Database could not be connected to. {"code":500,"exception":"SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)"} 
[2022-01-29 20:24:38+01:00] INFO: Installer API request received {"method":"POST","endpoint":"checkDatabase"} 
[2022-01-29 20:24:38+01:00] NOTICE: Check database connection  
[2022-01-29 20:24:38+01:00] INFO: Installer API request received {"method":"GET","endpoint":"checkWriteAccess"} 
[2022-01-29 20:24:38+01:00] NOTICE: Current working directory is writable.  
[2022-01-29 20:24:39+01:00] NOTICE: Found 0 table(s) {"tables":""} 
[2022-01-29 20:24:39+01:00] NOTICE: Database connection established and verified empty  
[2022-01-29 20:24:39+01:00] INFO: Installer API request received {"method":"POST","endpoint":"downloadWinter"} 
[2022-01-29 20:24:39+01:00] NOTICE: Try downloading Winter CMS archive  
[2022-01-29 20:24:39+01:00] NOTICE: Downloading Winter ZIP via cURL {"url":"https://github.com/wintercms/winter/archive/refs/heads/1.1.zip"} 
[2022-01-29 20:24:43+01:00] NOTICE: Winter CMS ZIP file downloaded {"path":"B:\\xampp\\htdocs\\winter\\.wintercms\\winter.zip"} 
[2022-01-29 20:24:43+01:00] INFO: Installer API request received {"method":"POST","endpoint":"extractWinter"} 
[2022-01-29 20:24:43+01:00] NOTICE: Begin extracting Winter CMS archive  
[2022-01-29 20:24:45+01:00] NOTICE: Move subfoldered files into position {"subfolder":"winter-1.1/"} 
[2022-01-29 20:24:45+01:00] NOTICE: Remove ZIP subfolder {"subfolder":"winter-1.1/"} 
[2022-01-29 20:24:45+01:00] NOTICE: Make artisan command-line tool executable {"path":"B:\\xampp\\htdocs\\winter\\.wintercms\\artisan"} 
[2022-01-29 20:24:45+01:00] NOTICE: Remove Composer Merge plugin from composer.json if found  
[2022-01-29 20:24:45+01:00] NOTICE: Found merge plugin in required packages - removing  
[2022-01-29 20:24:45+01:00] NOTICE: Found merge plugin config in "extra" config definition - removing  
[2022-01-29 20:24:45+01:00] INFO: Installer API request received {"method":"POST","endpoint":"lockDependencies"} 
[2022-01-29 20:24:45+01:00] NOTICE: Create Composer instance  
[2022-01-29 20:24:45+01:00] NOTICE: Set memory limit to 1.5GB  
[2022-01-29 20:24:45+01:00] NOTICE: Set work directory for Composer {"path":"B:\\xampp\\htdocs\\winter\\.wintercms"} 
[2022-01-29 20:24:45+01:00] NOTICE: Create home/cache directory for Composer {"path":"B:\\xampp\\htdocs\\winter\\.wintercms\\.composer"} 
[2022-01-29 20:24:45+01:00] NOTICE: Set home/cache directory for Composer {"path":"B:\\xampp\\htdocs\\winter\\.wintercms\\.composer"} 
[2022-01-29 20:24:45+01:00] NOTICE: Run Composer "update" command - generate only a lockfile  
[2022-01-29 20:24:54+01:00] NOTICE: Locked Composer packages {"numPackages":105,"lockFile":"B:\\xampp\\htdocs\\winter\\.wintercms\\composer.lock"} 
[2022-01-29 20:24:54+01:00] INFO: Installer API request received {"method":"POST","endpoint":"installDependencies"} 
[2022-01-29 20:24:54+01:00] NOTICE: Create Composer instance  
[2022-01-29 20:24:54+01:00] NOTICE: Set memory limit to 1.5GB  
[2022-01-29 20:24:54+01:00] NOTICE: Set work directory for Composer {"path":"B:\\xampp\\htdocs\\winter\\.wintercms"} 
[2022-01-29 20:24:54+01:00] NOTICE: Set home/cache directory for Composer {"path":"B:\\xampp\\htdocs\\winter\\.wintercms\\.composer"} 
[2022-01-29 20:24:54+01:00] NOTICE: Run Composer "install" command - install from lockfile  
[2022-01-29 20:25:26+01:00] NOTICE: Installed Composer packages {"numPackages":105} 
[2022-01-29 20:25:26+01:00] INFO: Installer API request received {"method":"POST","endpoint":"setupConfig"} 
[2022-01-29 20:25:26+01:00] NOTICE: Booting Laravel framework  
[2022-01-29 20:25:26+01:00] NOTICE: Loading autoloader  
[2022-01-29 20:25:26+01:00] NOTICE: Bootstrapping kernel  

```

**Comment by stareu** [comment]
More exact info in DevTools:

```
(1/1) FatalErrorExceptionDuring inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Pagination\AbstractPaginator::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in B:\xampp\htdocs\winter\.wintercms\vendor\laravel\framework\src\Illuminate\Pagination\AbstractPaginator.php:599Stack trace:#0 B:\xampp\htdocs\winter\.wintercms\vendor\laravel\framework\src\Illuminate\Pagination\Paginator.php(14): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Return type of ...', 'B:\\xampp\\htdocs...', 599)#1 B:\xampp\htdocs\winter\install\api\vendor\composer\ClassLoader.php(571): include('B:\\xampp\\htdocs...')#2 B:\xampp\htdocs\winter\install\api\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('B:\\xampp\\htdocs...')#3 B:\xampp\htdocs\winter\.wintercms\vendor\laravel\framework\src\Illuminate\Pagination\PaginationServiceProvider.php(32): Composer\Autoload\ClassLoader->loadClass('Illuminate\\Pagi...')#4 B:\xampp\htdocs\winter\.wintercms\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(616): Illuminate\Pagination\PaginationServiceProvider->register()#5 B:\xampp\htdocs\winter\.wintercms\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php(75): Illuminate\Foundation\Application->register(Object(Illuminate\Pagination\PaginationServiceProvider))#6 B:\xampp\htdocs\winter\.wintercms\vendor\winter\storm\src\Foundation\Application.php(401): Illuminate\Foundation\ProviderRepository->load(Array)#7 B:\xampp\htdocs\winter\.wintercms\vendor\winter\storm\src\Foundation\Application.php(409): Winter\Storm\Foundation\Application->registerConfiguredProviders(true)#8 B:\xampp\htdocs\winter\.wintercms\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\RegisterProviders.php(17): Winter\Storm\Foundation\Application->registerConfiguredProviders()#9 B:\xampp\htdocs\winter\.wintercms\vendor\winter\storm\src\Foundation\Application.php(127): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Winter\Storm\Foundation\Application))#10 B:\xampp\htdocs\winter\.wintercms\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(320): Winter\Storm\Foundation\Application->bootstrapWith(Array)#11 B:\xampp\htdocs\winter\install\api\src\Api.php(984): Illuminate\Foundation\Console\Kernel->bootstrap()#12 B:\xampp\htdocs\winter\install\api\src\Api.php(528): Winter\Installer\Api->bootFramework()#13 B:\xampp\htdocs\winter\install\api\src\Api.php(87): Winter\Installer\Api->postSetupConfig()#14 B:\xampp\htdocs\winter\install\api.php(10): Winter\Installer\Api->request()#15 {main}
--
in Paginator.php line 14

```

**Comment by LukeTowers** [comment]
What version of PHP are you trying to use @stareu?

**Comment by bennothommo** [comment]
@stareu Winter CMS is currently not compatible with PHP 8.1, due to the underlying Laravel version not supporting it. We will be deploying a new branch of Winter with Laravel 9 which will support it, but until then, you will need to use PHP 7.4 or 8.0.

**Comment by stareu** [comment]
@bennothommo @LukeTowers 
Thank you!
It was PHP 8.1.2.
I reinstalled XAMPP with PHP 8.0.15 and it helped!
